"""master admin test

Revision ID: 871b2fa6b372
Revises: 1e6c1a0562ea
Create Date: 2022-07-21 16:23:19.990108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871b2fa6b372'
down_revision = '1e6c1a0562ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'serverId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channels', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('messages', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'channelId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(length=1500),
               nullable=False)
    op.alter_column('servers', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('servers', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('servers', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(length=1500),
               nullable=True)
    op.alter_column('messages', 'channelId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channels', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('channels', 'serverId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
