"""empty message

Revision ID: 7c19da8725a7
Revises: 54031acd6ea5
Create Date: 2022-07-22 13:26:20.722683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c19da8725a7'
down_revision = '54031acd6ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serverusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('adminStatus', sa.Boolean(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['serverId'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('server_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serverId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adminStatus', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('muted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['serverId'], ['servers.id'], name='server_users_serverId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='server_users_userId_fkey'),
    sa.PrimaryKeyConstraint('id', 'userId', 'serverId', name='server_users_pkey')
    )
    op.drop_table('serverusers')
    # ### end Alembic commands ###
