"""empty message

Revision ID: 2399c0ff37a7
Revises: bf5d9270539a
Create Date: 2022-07-27 16:28:25.417702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2399c0ff37a7'
down_revision = 'bf5d9270539a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friends_userId_fkey', 'friends', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('friends_userId_fkey', 'friends', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
