"""empty message

Revision ID: 54031acd6ea5
Revises: 7b6ba0697617
Create Date: 2022-07-21 17:02:55.760275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54031acd6ea5'
down_revision = '7b6ba0697617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('master_admin', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servers', 'users', ['master_admin'], ['id'])
    op.drop_column('servers', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('test', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'master_admin')
    # ### end Alembic commands ###
