"""empty message

Revision ID: 7b6ba0697617
Revises: 871b2fa6b372
Create Date: 2022-07-21 16:58:57.158856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6ba0697617'
down_revision = '871b2fa6b372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('test', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'test')
    # ### end Alembic commands ###
